MvcCodeFirst/Controllers/ActionResultsController.cs
using MvcCodeFirst.Models;
using MvcCodeFirst.Models.Managers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcCodeFirst.Controllers
{
    public class ActionResultsController : Controller
    {
        DatabaseContext db = new DatabaseContext();
        // GET: ActionResults
        public ActionResult Index()
        {
            return View();
        }

        public RedirectResult Home()
        {
            return Redirect("http://www.google.com");
        }

        public ActionResult Index3()
        {
            return View();
        }
        public JsonResult Index4()
        {
            Kisiler k = new Kisiler();
            k.Ad = "Berkay";
            k.Soyad = "Akdeniz";
            k.Yas = 26;
            return Json(k,JsonRequestBehavior.AllowGet);
        }

        public ActionResult Dosyalar()
        {
            ViewBag.id = TempData["id"];
            int id = Convert.ToInt32(ViewBag.id);
            List<Adresler> Adresler = (from x in db.Adresler where x.KisiId == id select x).ToList();
            return View(Adresler);
        }

        public ActionResult Dosyalar4(int Kisi)
        {
            TempData["id"] = Kisi;
            List<Adresler> Adresler = (from x in db.Adresler where x.KisiId == Kisi select x).ToList();
            return RedirectToAction("Dosyalar",Adresler);
        }
        public FileResult Dosyalar2()
        {
            string pdf = Server.MapPath("~/Files/CVim (1).pdf");
            return new FilePathResult(pdf,"application/pdf");
        }

        public FileStreamResult Dosyalar3()
        {
            string metin = "Denem Mesajı";
            System.IO.MemoryStream memo = new System.IO.MemoryStream();

            byte[] bytemetin = System.Text.Encoding.UTF8.GetBytes(metin);

            memo.Write(bytemetin, 0, bytemetin.Length);
            memo.Position = 0;
            FileStreamResult stream = new FileStreamResult(memo, "text/plain");

            stream.FileDownloadName = "Deneme.txt";

            return stream;
        }

        public PartialViewResult KategoriPartial()
        {
            return PartialView("_KategorilerPartial");
        }
        public JavaScriptResult JavaScript()
        {
            return JavaScript("alert('JavaScriptResult Örneği')");
        }
    }
}

MvcCodeFirst/Controllers/HomeController.cs
using MvcCodeFirst.Filter;
using MvcCodeFirst.Models;
using MvcCodeFirst.Models.Managers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.ModelBinding;
using System.Web.Mvc;

namespace MvcCodeFirst.Controllers
{
    public class HomeController : Controller
    {
        //Test Branch indeki development
        DatabaseContext db = new DatabaseContext();
        // GET: Home
        [AuthFilter, ActFilter,ExcFilter]
        public ActionResult Index()
        {
            //DatabaseContext db = new DatabaseContext();
            List<Kisiler> KisiListe = db.Kisiler.ToList();
            return View(KisiListe);
        }
        
        public ActionResult Add()
        {

            return View();
        }
        [HttpPost]
        public ActionResult Add(string ad,string soyad,string yas)
        {
            Kisiler ben = new Kisiler();
            ben.Ad = ad;
            ben.Soyad = soyad;
            ben.Yas = Convert.ToInt32(yas);
            db.Kisiler.Add(ben);
            db.SaveChanges();

            return RedirectToAction("Index", "Home");
        }

        public ActionResult Duzenle(int Kisiid)
        {
            Kisiler kisi = db.Kisiler.Where(k => k.Id == Kisiid).FirstOrDefault();
            return View(kisi);
        }
        [HttpPost]
        public ActionResult Duzenle(Kisiler kisim,int kisiId)
        {
            Kisiler eski = db.Kisiler.Where(k => k.Id == kisiId).FirstOrDefault();
            eski.Ad = kisim.Ad;
            eski.Soyad = kisim.Soyad;
            eski.Yas = kisim.Yas;
            db.SaveChanges();
            return RedirectToAction("Index","Home");
        }

        public ActionResult Sil(int Kisiid)
        {
            Kisiler kisi = db.Kisiler.Where(k => k.Id == Kisiid).FirstOrDefault();
            return View(kisi);
        }
        [HttpPost,ActionName("Sil")]
        public ActionResult Sil1(int kisiId)
        {
            Kisiler sil = db.Kisiler.Where(k => k.Id == kisiId).FirstOrDefault();
            if (sil != null)
            {
                db.Kisiler.Remove(sil);
            }
            db.SaveChanges();
            return RedirectToAction("Index", "Home");
        }
      
        public ActionResult Login()
        {
            return View(new Kullanici());
        }
        [HttpPost]
        public ActionResult Login(Kullanici kul)
        {
            bool kullaniciadi = false;
            bool sifre = false;

            Kullanici k = db.Kullanicis.FirstOrDefault(x => x.Eposta.Equals(kul.Eposta));

            if (k != null)
            {
                kullaniciadi = true;

                if (db.Kullanicis.FirstOrDefault(x => x.Sifre.Equals(kul.Sifre)) != null)
                {
                    sifre = true;
                }
            }


            if (!kullaniciadi)
            {
                ModelState.AddModelError("", "Hatalı e-posta adresi");
                return View(kul);
            }

            else if (!sifre)
            {
                ModelState.AddModelError("", "Hatalı sifre");
                return View(kul);
            }
            else
            {
                Session["kul"] = k;
                return RedirectToAction("Index", "Home");
            }

        }

        public ActionResult Error()
        {
            if (TempData["error"] == null)
            {
                return View();//baska bi hata mesajı vercek aslında
            }

            Exception model = TempData["error"] as Exception;

           
            return View(model);
        }

    }
}

MvcCodeFirst/Views/ActionResults/Dosyalar.cshtml
@using MvcCodeFirst.Models
@model List<Adresler>
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Dosyalar</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <script src="~/ActionResults/JavaScript"></script>
</head>
<body>
    <div class="container">
        <h2>Dosyalar</h2>
        <hr />
        <div class="row">
            @Html.ActionLink("Pdf Dosya Indir", "Dosyalar2", "ActionResults")
        </div>
        <div class="row">
            @Html.ActionLink("Metin Dosyası Indir", "Dosyalar3", "ActionResults")
        </div>
    </div>
    @Html.Action("KategoriPartial")

    <br />
    <div class="container">
        <div class="row">
            <ul class="list-group">
                @if (Model != null)
                {
                    foreach (MvcCodeFirst.Models.Adresler adres in Model)
                    {
                        <li class="list-group-item">
                            <span class="glyphicon glyphicon-home"></span>
                            @adres.Adres
                        </li>
                    }
                }
            </ul>

        </div>
    </div>
</body>
</html>

MvcCodeFirst/Views/ActionResults/Home.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Home</title>
</head>
<body>
    <div> 
    </div>
</body>
</html>

MvcCodeFirst/Views/ActionResults/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div> 
    </div>
</body>
</html>

MvcCodeFirst/Views/ActionResults/Index3.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index3</title>
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
</head>
<body>
    <div>
        <input type="submit" value="JsonGetir" id="btnJson"/>
    </div>
    
    <script>
        $(function () {
            $("#btnJson").click(function () {
                $.ajax({
                    type: "GET",
                    url: "/ActionResults/Index4",
                    contentType: "application/json; charset=utf-8",
                    dataype: "json",
                    success: function (e) {
                        alert(e.Ad);
                        alert(e.Soyad);
                        alert(e.Yas);
                    }
                });
            });
        });
    </script>

</body>
</html>